set(HEADER_FILES
game_application/game_main.h
game_application/event_system.h
game_logic/actor.h
game_logic/arm_neon_ext_itunu.h
game_logic/systems_manager.h
game_logic/entity.h
game_logic/game_logic.h
game_logic/physics_system.h
game_logic/simd.h
game_logic/components/component_base.h
game_logic/components/position_component.h
game_logic/components/render_component.h
game_logic/components/component.h
game_logic/components/component_manager.h
game_logic/components/aabb_component.h
game_logic/components/velocity_component.h
game_logic/components/waypoint_component.h
game_logic/components/rotation_component.h
game_logic/components/scale_component.h
)