set(HEADER_FILES
    core/ilist.h
    core/irand.h
    core/istack.h
    core/simd.h
    game_application/event_system.h
    game_application/game_main.h
    game_application/input_system.h
    game_logic/components/aabb_component.h
    game_logic/components/ai_component.h
    game_logic/components/component.h
    game_logic/components/component_base.h
    game_logic/components/component_manager.h
    game_logic/components/force_component.h
    game_logic/components/grid_component.h
    game_logic/components/mass_component.h
    game_logic/components/position_component.h
    game_logic/components/render_component.h
    game_logic/components/rotation_component.h
    game_logic/components/scale_component.h
    game_logic/components/velocity_component.h
    game_logic/components/verlet_component.h
    game_logic/components/waypoint_component.h
    game_logic/entities/actor.h
    game_logic/entities/entity.h
    game_logic/game_logic.h
    game_logic/grid/dfs_maze.h
    game_logic/grid/grid.h
    game_logic/grid/wave_fn_collapse.h
    game_logic/process_manager.h
    game_logic/systems/systems_manager.h
    graphics/game_view.h
    graphics/human_view.h
    graphics/raylib_glue.h
    graphics/render_system.h
    physics/arm_neon_ext_itunu.h
    physics/gravity_system.h
    physics/physics_system.h
    resources/resource_manager.h
)
