set(SOURCE_FILES
game_application/event_system.c
game_application/game_main.c
game_logic/actor.c
game_logic/actor_manager.c
game_logic/entity.c
game_logic/network.c
game_logic/physics_system.c
game_logic/render_system.c
game_logic/systems_manager.c
game_logic/components/position_component.c
game_logic/components/render_component.c
game_logic/components/verlet_component.c
game_logic/components/component_manager.c
game_logic/components/component.c
game_logic/components/aabb_component.c
game_logic/components/velocity_component.c
game_logic/components/waypoint_component.c
game_logic/components/rotation_component.c
game_logic/components/scale_component.c
)