set(SOURCE_FILES
    core/ilist.c
    core/irand.c
    core/istack.c
    game_application/event_system.c
    game_application/game_main.c
    game_application/input_system.c
    game_logic/components/aabb_component.c
    game_logic/components/ai_component.c
    game_logic/components/component.c
    game_logic/components/component_manager.c
    game_logic/components/force_component.c
    game_logic/components/grid_component.c
    game_logic/components/mass_component.c
    game_logic/components/position_component.c
    game_logic/components/render_component.c
    game_logic/components/rotation_component.c
    game_logic/components/scale_component.c
    game_logic/components/velocity_component.c
    game_logic/components/verlet_component.c
    game_logic/components/waypoint_component.c
    game_logic/entities/actor.c
    game_logic/entities/actor_manager.c
    game_logic/entities/entity.c
    game_logic/game_logic.c
    game_logic/grid/grid.c
    game_logic/grid/wave_fn_collapse.c
    game_logic/process_manager.c
    game_logic/systems/ai_system.c
    game_logic/systems/systems_manager.c
    graphics/game_view.c
    graphics/human_view.c
    graphics/raylib_glue.c
    graphics/render_system.c
    graphics/resources.c
    network/network.c
    physics/gravity_system.c
    physics/physics_system.c
    resources/resource_manager.c
)
